# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ankidets/EPITECH/PROJECTS/IndieStudio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ankidets/EPITECH/PROJECTS/IndieStudio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ankidets/EPITECH/PROJECTS/IndieStudio/CMakeFiles /home/ankidets/EPITECH/PROJECTS/IndieStudio//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ankidets/EPITECH/PROJECTS/IndieStudio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

src/engine/Engine.o: src/engine/Engine.cpp.o
.PHONY : src/engine/Engine.o

# target to build an object file
src/engine/Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/Engine.cpp.o
.PHONY : src/engine/Engine.cpp.o

src/engine/Engine.i: src/engine/Engine.cpp.i
.PHONY : src/engine/Engine.i

# target to preprocess a source file
src/engine/Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/Engine.cpp.i
.PHONY : src/engine/Engine.cpp.i

src/engine/Engine.s: src/engine/Engine.cpp.s
.PHONY : src/engine/Engine.s

# target to generate assembly for a file
src/engine/Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/Engine.cpp.s
.PHONY : src/engine/Engine.cpp.s

src/engine/objects/Bomb/Bomb.o: src/engine/objects/Bomb/Bomb.cpp.o
.PHONY : src/engine/objects/Bomb/Bomb.o

# target to build an object file
src/engine/objects/Bomb/Bomb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Bomb/Bomb.cpp.o
.PHONY : src/engine/objects/Bomb/Bomb.cpp.o

src/engine/objects/Bomb/Bomb.i: src/engine/objects/Bomb/Bomb.cpp.i
.PHONY : src/engine/objects/Bomb/Bomb.i

# target to preprocess a source file
src/engine/objects/Bomb/Bomb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Bomb/Bomb.cpp.i
.PHONY : src/engine/objects/Bomb/Bomb.cpp.i

src/engine/objects/Bomb/Bomb.s: src/engine/objects/Bomb/Bomb.cpp.s
.PHONY : src/engine/objects/Bomb/Bomb.s

# target to generate assembly for a file
src/engine/objects/Bomb/Bomb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Bomb/Bomb.cpp.s
.PHONY : src/engine/objects/Bomb/Bomb.cpp.s

src/engine/objects/Brick/Brick.o: src/engine/objects/Brick/Brick.cpp.o
.PHONY : src/engine/objects/Brick/Brick.o

# target to build an object file
src/engine/objects/Brick/Brick.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Brick/Brick.cpp.o
.PHONY : src/engine/objects/Brick/Brick.cpp.o

src/engine/objects/Brick/Brick.i: src/engine/objects/Brick/Brick.cpp.i
.PHONY : src/engine/objects/Brick/Brick.i

# target to preprocess a source file
src/engine/objects/Brick/Brick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Brick/Brick.cpp.i
.PHONY : src/engine/objects/Brick/Brick.cpp.i

src/engine/objects/Brick/Brick.s: src/engine/objects/Brick/Brick.cpp.s
.PHONY : src/engine/objects/Brick/Brick.s

# target to generate assembly for a file
src/engine/objects/Brick/Brick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Brick/Brick.cpp.s
.PHONY : src/engine/objects/Brick/Brick.cpp.s

src/engine/objects/Entities/Entity.o: src/engine/objects/Entities/Entity.cpp.o
.PHONY : src/engine/objects/Entities/Entity.o

# target to build an object file
src/engine/objects/Entities/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Entities/Entity.cpp.o
.PHONY : src/engine/objects/Entities/Entity.cpp.o

src/engine/objects/Entities/Entity.i: src/engine/objects/Entities/Entity.cpp.i
.PHONY : src/engine/objects/Entities/Entity.i

# target to preprocess a source file
src/engine/objects/Entities/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Entities/Entity.cpp.i
.PHONY : src/engine/objects/Entities/Entity.cpp.i

src/engine/objects/Entities/Entity.s: src/engine/objects/Entities/Entity.cpp.s
.PHONY : src/engine/objects/Entities/Entity.s

# target to generate assembly for a file
src/engine/objects/Entities/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Entities/Entity.cpp.s
.PHONY : src/engine/objects/Entities/Entity.cpp.s

src/engine/objects/Entities/Ia/Ia.o: src/engine/objects/Entities/Ia/Ia.cpp.o
.PHONY : src/engine/objects/Entities/Ia/Ia.o

# target to build an object file
src/engine/objects/Entities/Ia/Ia.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Entities/Ia/Ia.cpp.o
.PHONY : src/engine/objects/Entities/Ia/Ia.cpp.o

src/engine/objects/Entities/Ia/Ia.i: src/engine/objects/Entities/Ia/Ia.cpp.i
.PHONY : src/engine/objects/Entities/Ia/Ia.i

# target to preprocess a source file
src/engine/objects/Entities/Ia/Ia.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Entities/Ia/Ia.cpp.i
.PHONY : src/engine/objects/Entities/Ia/Ia.cpp.i

src/engine/objects/Entities/Ia/Ia.s: src/engine/objects/Entities/Ia/Ia.cpp.s
.PHONY : src/engine/objects/Entities/Ia/Ia.s

# target to generate assembly for a file
src/engine/objects/Entities/Ia/Ia.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Entities/Ia/Ia.cpp.s
.PHONY : src/engine/objects/Entities/Ia/Ia.cpp.s

src/engine/objects/Entities/Player/Player.o: src/engine/objects/Entities/Player/Player.cpp.o
.PHONY : src/engine/objects/Entities/Player/Player.o

# target to build an object file
src/engine/objects/Entities/Player/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Entities/Player/Player.cpp.o
.PHONY : src/engine/objects/Entities/Player/Player.cpp.o

src/engine/objects/Entities/Player/Player.i: src/engine/objects/Entities/Player/Player.cpp.i
.PHONY : src/engine/objects/Entities/Player/Player.i

# target to preprocess a source file
src/engine/objects/Entities/Player/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Entities/Player/Player.cpp.i
.PHONY : src/engine/objects/Entities/Player/Player.cpp.i

src/engine/objects/Entities/Player/Player.s: src/engine/objects/Entities/Player/Player.cpp.s
.PHONY : src/engine/objects/Entities/Player/Player.s

# target to generate assembly for a file
src/engine/objects/Entities/Player/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Entities/Player/Player.cpp.s
.PHONY : src/engine/objects/Entities/Player/Player.cpp.s

src/engine/objects/GameObject.o: src/engine/objects/GameObject.cpp.o
.PHONY : src/engine/objects/GameObject.o

# target to build an object file
src/engine/objects/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/GameObject.cpp.o
.PHONY : src/engine/objects/GameObject.cpp.o

src/engine/objects/GameObject.i: src/engine/objects/GameObject.cpp.i
.PHONY : src/engine/objects/GameObject.i

# target to preprocess a source file
src/engine/objects/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/GameObject.cpp.i
.PHONY : src/engine/objects/GameObject.cpp.i

src/engine/objects/GameObject.s: src/engine/objects/GameObject.cpp.s
.PHONY : src/engine/objects/GameObject.s

# target to generate assembly for a file
src/engine/objects/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/GameObject.cpp.s
.PHONY : src/engine/objects/GameObject.cpp.s

src/engine/objects/PowerUp/PowerUp.o: src/engine/objects/PowerUp/PowerUp.cpp.o
.PHONY : src/engine/objects/PowerUp/PowerUp.o

# target to build an object file
src/engine/objects/PowerUp/PowerUp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/PowerUp/PowerUp.cpp.o
.PHONY : src/engine/objects/PowerUp/PowerUp.cpp.o

src/engine/objects/PowerUp/PowerUp.i: src/engine/objects/PowerUp/PowerUp.cpp.i
.PHONY : src/engine/objects/PowerUp/PowerUp.i

# target to preprocess a source file
src/engine/objects/PowerUp/PowerUp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/PowerUp/PowerUp.cpp.i
.PHONY : src/engine/objects/PowerUp/PowerUp.cpp.i

src/engine/objects/PowerUp/PowerUp.s: src/engine/objects/PowerUp/PowerUp.cpp.s
.PHONY : src/engine/objects/PowerUp/PowerUp.s

# target to generate assembly for a file
src/engine/objects/PowerUp/PowerUp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/PowerUp/PowerUp.cpp.s
.PHONY : src/engine/objects/PowerUp/PowerUp.cpp.s

src/engine/objects/Wall/Wall.o: src/engine/objects/Wall/Wall.cpp.o
.PHONY : src/engine/objects/Wall/Wall.o

# target to build an object file
src/engine/objects/Wall/Wall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Wall/Wall.cpp.o
.PHONY : src/engine/objects/Wall/Wall.cpp.o

src/engine/objects/Wall/Wall.i: src/engine/objects/Wall/Wall.cpp.i
.PHONY : src/engine/objects/Wall/Wall.i

# target to preprocess a source file
src/engine/objects/Wall/Wall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Wall/Wall.cpp.i
.PHONY : src/engine/objects/Wall/Wall.cpp.i

src/engine/objects/Wall/Wall.s: src/engine/objects/Wall/Wall.cpp.s
.PHONY : src/engine/objects/Wall/Wall.s

# target to generate assembly for a file
src/engine/objects/Wall/Wall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/objects/Wall/Wall.cpp.s
.PHONY : src/engine/objects/Wall/Wall.cpp.s

src/graphics/Display.o: src/graphics/Display.cpp.o
.PHONY : src/graphics/Display.o

# target to build an object file
src/graphics/Display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Display.cpp.o
.PHONY : src/graphics/Display.cpp.o

src/graphics/Display.i: src/graphics/Display.cpp.i
.PHONY : src/graphics/Display.i

# target to preprocess a source file
src/graphics/Display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Display.cpp.i
.PHONY : src/graphics/Display.cpp.i

src/graphics/Display.s: src/graphics/Display.cpp.s
.PHONY : src/graphics/Display.s

# target to generate assembly for a file
src/graphics/Display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Display.cpp.s
.PHONY : src/graphics/Display.cpp.s

src/graphics/Objects/Button.o: src/graphics/Objects/Button.cpp.o
.PHONY : src/graphics/Objects/Button.o

# target to build an object file
src/graphics/Objects/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Button.cpp.o
.PHONY : src/graphics/Objects/Button.cpp.o

src/graphics/Objects/Button.i: src/graphics/Objects/Button.cpp.i
.PHONY : src/graphics/Objects/Button.i

# target to preprocess a source file
src/graphics/Objects/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Button.cpp.i
.PHONY : src/graphics/Objects/Button.cpp.i

src/graphics/Objects/Button.s: src/graphics/Objects/Button.cpp.s
.PHONY : src/graphics/Objects/Button.s

# target to generate assembly for a file
src/graphics/Objects/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Button.cpp.s
.PHONY : src/graphics/Objects/Button.cpp.s

src/graphics/Objects/Cam.o: src/graphics/Objects/Cam.cpp.o
.PHONY : src/graphics/Objects/Cam.o

# target to build an object file
src/graphics/Objects/Cam.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Cam.cpp.o
.PHONY : src/graphics/Objects/Cam.cpp.o

src/graphics/Objects/Cam.i: src/graphics/Objects/Cam.cpp.i
.PHONY : src/graphics/Objects/Cam.i

# target to preprocess a source file
src/graphics/Objects/Cam.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Cam.cpp.i
.PHONY : src/graphics/Objects/Cam.cpp.i

src/graphics/Objects/Cam.s: src/graphics/Objects/Cam.cpp.s
.PHONY : src/graphics/Objects/Cam.s

# target to generate assembly for a file
src/graphics/Objects/Cam.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Cam.cpp.s
.PHONY : src/graphics/Objects/Cam.cpp.s

src/graphics/Objects/Mouse.o: src/graphics/Objects/Mouse.cpp.o
.PHONY : src/graphics/Objects/Mouse.o

# target to build an object file
src/graphics/Objects/Mouse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Mouse.cpp.o
.PHONY : src/graphics/Objects/Mouse.cpp.o

src/graphics/Objects/Mouse.i: src/graphics/Objects/Mouse.cpp.i
.PHONY : src/graphics/Objects/Mouse.i

# target to preprocess a source file
src/graphics/Objects/Mouse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Mouse.cpp.i
.PHONY : src/graphics/Objects/Mouse.cpp.i

src/graphics/Objects/Mouse.s: src/graphics/Objects/Mouse.cpp.s
.PHONY : src/graphics/Objects/Mouse.s

# target to generate assembly for a file
src/graphics/Objects/Mouse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Mouse.cpp.s
.PHONY : src/graphics/Objects/Mouse.cpp.s

src/graphics/Objects/Musics.o: src/graphics/Objects/Musics.cpp.o
.PHONY : src/graphics/Objects/Musics.o

# target to build an object file
src/graphics/Objects/Musics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Musics.cpp.o
.PHONY : src/graphics/Objects/Musics.cpp.o

src/graphics/Objects/Musics.i: src/graphics/Objects/Musics.cpp.i
.PHONY : src/graphics/Objects/Musics.i

# target to preprocess a source file
src/graphics/Objects/Musics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Musics.cpp.i
.PHONY : src/graphics/Objects/Musics.cpp.i

src/graphics/Objects/Musics.s: src/graphics/Objects/Musics.cpp.s
.PHONY : src/graphics/Objects/Musics.s

# target to generate assembly for a file
src/graphics/Objects/Musics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Musics.cpp.s
.PHONY : src/graphics/Objects/Musics.cpp.s

src/graphics/Objects/Noise.o: src/graphics/Objects/Noise.cpp.o
.PHONY : src/graphics/Objects/Noise.o

# target to build an object file
src/graphics/Objects/Noise.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Noise.cpp.o
.PHONY : src/graphics/Objects/Noise.cpp.o

src/graphics/Objects/Noise.i: src/graphics/Objects/Noise.cpp.i
.PHONY : src/graphics/Objects/Noise.i

# target to preprocess a source file
src/graphics/Objects/Noise.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Noise.cpp.i
.PHONY : src/graphics/Objects/Noise.cpp.i

src/graphics/Objects/Noise.s: src/graphics/Objects/Noise.cpp.s
.PHONY : src/graphics/Objects/Noise.s

# target to generate assembly for a file
src/graphics/Objects/Noise.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Noise.cpp.s
.PHONY : src/graphics/Objects/Noise.cpp.s

src/graphics/Objects/Picture.o: src/graphics/Objects/Picture.cpp.o
.PHONY : src/graphics/Objects/Picture.o

# target to build an object file
src/graphics/Objects/Picture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Picture.cpp.o
.PHONY : src/graphics/Objects/Picture.cpp.o

src/graphics/Objects/Picture.i: src/graphics/Objects/Picture.cpp.i
.PHONY : src/graphics/Objects/Picture.i

# target to preprocess a source file
src/graphics/Objects/Picture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Picture.cpp.i
.PHONY : src/graphics/Objects/Picture.cpp.i

src/graphics/Objects/Picture.s: src/graphics/Objects/Picture.cpp.s
.PHONY : src/graphics/Objects/Picture.s

# target to generate assembly for a file
src/graphics/Objects/Picture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Picture.cpp.s
.PHONY : src/graphics/Objects/Picture.cpp.s

src/graphics/Objects/Sprite.o: src/graphics/Objects/Sprite.cpp.o
.PHONY : src/graphics/Objects/Sprite.o

# target to build an object file
src/graphics/Objects/Sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Sprite.cpp.o
.PHONY : src/graphics/Objects/Sprite.cpp.o

src/graphics/Objects/Sprite.i: src/graphics/Objects/Sprite.cpp.i
.PHONY : src/graphics/Objects/Sprite.i

# target to preprocess a source file
src/graphics/Objects/Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Sprite.cpp.i
.PHONY : src/graphics/Objects/Sprite.cpp.i

src/graphics/Objects/Sprite.s: src/graphics/Objects/Sprite.cpp.s
.PHONY : src/graphics/Objects/Sprite.s

# target to generate assembly for a file
src/graphics/Objects/Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Sprite.cpp.s
.PHONY : src/graphics/Objects/Sprite.cpp.s

src/graphics/Objects/Text.o: src/graphics/Objects/Text.cpp.o
.PHONY : src/graphics/Objects/Text.o

# target to build an object file
src/graphics/Objects/Text.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Text.cpp.o
.PHONY : src/graphics/Objects/Text.cpp.o

src/graphics/Objects/Text.i: src/graphics/Objects/Text.cpp.i
.PHONY : src/graphics/Objects/Text.i

# target to preprocess a source file
src/graphics/Objects/Text.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Text.cpp.i
.PHONY : src/graphics/Objects/Text.cpp.i

src/graphics/Objects/Text.s: src/graphics/Objects/Text.cpp.s
.PHONY : src/graphics/Objects/Text.s

# target to generate assembly for a file
src/graphics/Objects/Text.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphics/Objects/Text.cpp.s
.PHONY : src/graphics/Objects/Text.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/map/Map.o: src/map/Map.cpp.o
.PHONY : src/map/Map.o

# target to build an object file
src/map/Map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/map/Map.cpp.o
.PHONY : src/map/Map.cpp.o

src/map/Map.i: src/map/Map.cpp.i
.PHONY : src/map/Map.i

# target to preprocess a source file
src/map/Map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/map/Map.cpp.i
.PHONY : src/map/Map.cpp.i

src/map/Map.s: src/map/Map.cpp.s
.PHONY : src/map/Map.s

# target to generate assembly for a file
src/map/Map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/map/Map.cpp.s
.PHONY : src/map/Map.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bomberman"
	@echo "... src/engine/Engine.o"
	@echo "... src/engine/Engine.i"
	@echo "... src/engine/Engine.s"
	@echo "... src/engine/objects/Bomb/Bomb.o"
	@echo "... src/engine/objects/Bomb/Bomb.i"
	@echo "... src/engine/objects/Bomb/Bomb.s"
	@echo "... src/engine/objects/Brick/Brick.o"
	@echo "... src/engine/objects/Brick/Brick.i"
	@echo "... src/engine/objects/Brick/Brick.s"
	@echo "... src/engine/objects/Entities/Entity.o"
	@echo "... src/engine/objects/Entities/Entity.i"
	@echo "... src/engine/objects/Entities/Entity.s"
	@echo "... src/engine/objects/Entities/Ia/Ia.o"
	@echo "... src/engine/objects/Entities/Ia/Ia.i"
	@echo "... src/engine/objects/Entities/Ia/Ia.s"
	@echo "... src/engine/objects/Entities/Player/Player.o"
	@echo "... src/engine/objects/Entities/Player/Player.i"
	@echo "... src/engine/objects/Entities/Player/Player.s"
	@echo "... src/engine/objects/GameObject.o"
	@echo "... src/engine/objects/GameObject.i"
	@echo "... src/engine/objects/GameObject.s"
	@echo "... src/engine/objects/PowerUp/PowerUp.o"
	@echo "... src/engine/objects/PowerUp/PowerUp.i"
	@echo "... src/engine/objects/PowerUp/PowerUp.s"
	@echo "... src/engine/objects/Wall/Wall.o"
	@echo "... src/engine/objects/Wall/Wall.i"
	@echo "... src/engine/objects/Wall/Wall.s"
	@echo "... src/graphics/Display.o"
	@echo "... src/graphics/Display.i"
	@echo "... src/graphics/Display.s"
	@echo "... src/graphics/Objects/Button.o"
	@echo "... src/graphics/Objects/Button.i"
	@echo "... src/graphics/Objects/Button.s"
	@echo "... src/graphics/Objects/Cam.o"
	@echo "... src/graphics/Objects/Cam.i"
	@echo "... src/graphics/Objects/Cam.s"
	@echo "... src/graphics/Objects/Mouse.o"
	@echo "... src/graphics/Objects/Mouse.i"
	@echo "... src/graphics/Objects/Mouse.s"
	@echo "... src/graphics/Objects/Musics.o"
	@echo "... src/graphics/Objects/Musics.i"
	@echo "... src/graphics/Objects/Musics.s"
	@echo "... src/graphics/Objects/Noise.o"
	@echo "... src/graphics/Objects/Noise.i"
	@echo "... src/graphics/Objects/Noise.s"
	@echo "... src/graphics/Objects/Picture.o"
	@echo "... src/graphics/Objects/Picture.i"
	@echo "... src/graphics/Objects/Picture.s"
	@echo "... src/graphics/Objects/Sprite.o"
	@echo "... src/graphics/Objects/Sprite.i"
	@echo "... src/graphics/Objects/Sprite.s"
	@echo "... src/graphics/Objects/Text.o"
	@echo "... src/graphics/Objects/Text.i"
	@echo "... src/graphics/Objects/Text.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/map/Map.o"
	@echo "... src/map/Map.i"
	@echo "... src/map/Map.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

