name: Tests

on: [push, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if it builds
        run: |
          rm -rf build; mkdir -p build && cd build && cmake .. && make
      - name: Push to main repo
        if: success()
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2025/B-YEP-400-NCY-4-1-indiestudio-cedric.ulrich.git
          ssh_private_key:
            ${{ secrets.NODUMP }}
